AllCops:
  TargetRubyVersion: 2.4

  Exclude:
    - 'spec/dummy/**/*'

    # c.f. https://github.com/rubocop-hq/rubocop/blob/v0.72.0/config/default.yml#L60-L63
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'

Layout/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false
